### ISSUE TITLE
_run_cmd() does not seem to exist

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.vcs#18]
Originally reported by: **Michael Hoffman (BitBucket: [hoffman](http://bitbucket.org/hoffman), GitHub: [hoffman](http://github.com/hoffman))**

---

I tried to use something like the `_run_cmd()` snippet suggested in the readme to make my own version tag. This did not work.

```
Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    entry_points=entry_points
  File "/mnt/work1/software/python/2.7/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 243, in __init__
  File "/mnt/work1/software/python/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 277, in finalize_options
  File "/scratch/mhoffman/sandbox/hgtools/hgtools/plugins.py", line 110, in version_calc
    dist.metadata.version = calculate_version(options)
  File "/scratch/mhoffman/sandbox/hgtools/hgtools/plugins.py", line 96, in calculate_version
    version = version_handler(mgr, options)
  File "setup.py", line 55, in calc_version
    id_num = hg_id(mgr, "num")
  File "setup.py", line 52, in hg_id
    return mgr._run_cmd([mgr.exe, "id", "--%s" % kind]).strip()
AttributeError: 'MercurialManager' object has no attribute '_run_cmd'
```

Looks like it may have been replaced by `_invoke()`.

---
- Bitbucket: https://bitbucket.org/jaraco/hgtools/issue/18

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Update documentation to reflect newer APIs and support for Git. Fixes #18
