### ISSUE TITLE
hgtools fails to invoke 'hg' on Mac OS X in virtualenv

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.vcs#7]
Originally reported by: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

When developing or installing an hgtools-enabled project on Mac OS X in a virtualenv that's a different Python version than the version where 'hg' is installed, it may fail with the (somewhat uninformative) error:

```
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    , setup_requires = ['hgtools']
  File "/Users/whit537/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/whit537/workbench/unfoldR/venv/lib/python2.7/site-packages/distribute-0.6.16-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/Users/whit537/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/Users/whit537/workbench/unfoldR/venv/lib/python2.7/site-packages/distribute-0.6.16-py2.7.egg/setuptools/dist.py", line 258, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/whit537/workbench/unfoldR/hgtools-1.1.2-py2.7.egg/hgtools/plugins.py", line 98, in version_calc
    dist.metadata.version = calculate_version(options)
  File "/Users/whit537/workbench/unfoldR/hgtools-1.1.2-py2.7.egg/hgtools/plugins.py", line 83, in calculate_version
    mgr = managers.HGRepoManager.get_first_valid_manager()
  File "/Users/whit537/workbench/unfoldR/hgtools-1.1.2-py2.7.egg/hgtools/managers.py", line 49, in get_first_valid_manager
    return next(HGRepoManager.get_valid_managers(location))
StopIteration
```

Upon further investigation, it was found that the subprocess calls to 'hg version' were failing with this traceback:

```
 Traceback (most recent call last):
  File "/usr/local/bin/hg", line 5, in <module>
    import pkg_resources
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 698, in <module>
    the platform/python version defined at initialization are added.
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 701, in Environment
    search_path = sys.path
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 96, in get_supported_platform
    'Environment', 'WorkingSet', 'ResourceManager',
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 222, in get_build_platform
    dversion = int(provDarwin.group(1))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/util.py", line 97, in get_platform
    cfgvars = get_config_vars()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/sysconfig.py", line 525, in get_config_vars
    func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/sysconfig.py", line 408, in _init_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.4" but "10.6" during configure
```

---
- Bitbucket: https://bitbucket.org/jaraco/hgtools/issue/7

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Upon investigation, it was found that in the distutils context, the MACOSX_DEPLOYMENT_TARGET environment variable is set using putenv, so even though the variable doesn't appear in os.environ, it gets passed to the child process, which disrupts the execution of 'hg version'. The underlying error can be recreated by invoking the following command:

{{{
MACOSX_DEPLOYMENT_TARGET=10.4 hg version
}}}

It could be that there's a bug in pkg_resources that should be fixed to prevent that environment variable from disrupting the simple execution of a command.

On the other hand, it looks like hgtools can work around the issue by explicitly passing an environment when invoking the 'hg' command.

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Explicitly pass a copy of the environment. Workaround for setuptools bug in pkg_resources. Fixes #7.

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Removing version: 1.1 (automated comment)

**Comment by jaraco** [comment]
I'm able to confirm that the issue no longer exists, so the workaround can be removed:

```
 @ env MACOSX_DEPLOYMENT_TARGET=10.4 hg version
Mercurial Distributed SCM (version 6.5.2)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2023 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
